### ISSUE TITLE
Questions on trailing stop

### ISSUE THREAD

**Issue by Mothluin** [Thornsnake/MCRBot#4]
Hi
I contacted you on Reddit to ask a few questions, but I guess this is a more appropriate space.
- Would it be possible to log whether Trailing Stop is armed or not?
- If the Trailing Stop is armed, I change its parameters and restart the bot, will it still be armed? Based on your reply at #3, I'd say yes because the relevant data will still be stored in /data/PortfolioATH.json. But maybe the outcome depends on how much MIN_PROFIT and MAX_DROP change

I also had some suggestions to improve your installation guide, based on my experience:
- On my last attempt, I decided to install node.js v14.x from the get go. That proved to be a winning strategy. If you install node.js from repo, then force install v14.x over it, I always had issues with the nodejs-docs package
- npm gets installed automatically with node.js, but you have to update it with command: `npm install -g npm@latest`

Thanks

**Comment by Thornsnake** [comment]
I have added a log and webhook message for arming the trailing stop. You can update the bot with `sh update.sh` and then copy over the relevant config options from the `/template/_config.ts` file into the `config.ts` file.

If the trailing stop is armed, it will stay armed, until it triggers. Changing the parameters in the config file after the fact, will not disarm it. If you want to manually disarm it, open the `/data/PortfolioATH.json` file and change the values there accordingly.

The file will look something like this:
```
{
    "active": true,
    "allTimeHigh": 49771.20425766598,
    "investment": 35652.60341530497,
    "resume": 0,
    "triggered": false
}
```
If the trailing stop gets armed, the `active` option will be set to true. Setting it to false will disarm it. You need to make sure it doesn't get instantly armed again though by also changing the `allTimeHigh` and `investment` option.

The way it works is that the bot compares the `investment` value (the total worth of money the bot DCAed) to the `allTimeHigh` value (the highest value your portfolio ever had) and if that percentage is higher than what you've set for `MIN_PROFIT` in the settings, the trailing stop will be activated.

From that moment on, the `investment` option doesn't matter anymore. All that matters now for the bot to actually trigger the trailing stop is for the current portfolio worth (checked by default every 60 seconds) to go lower than the `allTimeHigh` value by the percentage you've set for `MAX_DROP` in the options.

If it does that, the trailing stop will trigger. The `resume` option will be set to the time from now plus the hours you've set for the `RESUME` option in the config and the `triggered` state will change to true.

As soon as the `RESUME` time has been reached, the PortfolioATH file will be reset and the bot will start to DCA from the start.
```
{
    "active": false,
    "allTimeHigh": 0,
    "investment": 0,
    "resume": 0,
    "triggered": false
}
```

Regarding the v14 issue, I don't know what's causing your nodejs-docs issue, but that's a problem the nodejs devs should fix. I would like to avoid asking the user to install v14 from the get go, because if there's already a newer version set as a default for his system, it would be a downgrade.

I've removed the installation remarks for NPM. Those are really not needed and the error you get for attempting to install it when it's already installed might be confusing.

**Comment by Mothluin** [comment]
Hi
Following your guidance above and in #3, a couple days ago I manually edited the PortfolioATH.json file and changed the `active` flag to true.
Even if not suggested, I also restarted the bot.

Now I see the bot sold everything according to the `MAX_DROP` setting tonight.
Or at least it claimed so:

```
2021-11-08T23:45:08: [CHECK] Rebalance not necessary
2021-11-08T23:46:00: Trailing stop hit, selling portfolio
2021-11-08T23:46:00: Portfolio sold, trading will resume in 48 hours
```

The PortfolioATH.json was also updated (`triggered` flag):

```
{
  "active":true,
  "allTimeHigh":522.68891667892,
  "investment":398.76984732744006,
  "resume":1636587960894,
  "triggered":true
}
```

However when I checked my portfolio on the Exchange today, I saw all the coins were still there.
How could this be?

Now the bot is just idling for 48 hours (as per my configuration) and will likely resume the trading afterwards.
Since it won't find any USDT, though, it will just start again with rebalancing.
The PortfolioATH.json file will also be reset.

A couple questions:

- How will the `investment` parameter in PortfolioATH.json be set then? That is key to arm future trailing stops
- Should I tinker with the PortfolioATH.json file again and force the bot to restart rebalancing by tweaking the `resume` flag?

I updated the bot to the latest version recently.

Thanks

**Comment by Thornsnake** [comment]
I just double checked the code for errors and triggered the trailing stop with active debugging. Everything should be working fine.

The time the stop was triggered was around the time the exchange had downtime and was throwing 504s for the website. I am not sure if that might have had something to do with it. The bot might have received and empty account balance due to the bug (which means portfolio worth of zero), then attempted to sell, but since it found no coins to sell, it simply did nothing but start the waiting time in the end.

I don't have another explanation, but will continue investigating.

Do you by any chance have something in your error log?

**Comment by Mothluin** [comment]
Let me see....

**Comment by Mothluin** [comment]
Nope.
My `mothluin-error.log` is completely empty.

Oh wait... that's only the most current one.
Let me check the others...

```
2021-11-08T12:00:30: Error - timeout of 30000ms exceeded
2021-11-08T15:40:30: Error - timeout of 30000ms exceeded
2021-11-08T19:40:30: Error - timeout of 30000ms exceeded
2021-11-08T20:10:31: Error - timeout of 30000ms exceeded
2021-11-08T20:30:31: Error - timeout of 30000ms exceeded
2021-11-08T20:45:31: Error - timeout of 30000ms exceeded
2021-11-08T20:50:30: Error - timeout of 30000ms exceeded
2021-11-08T20:55:30: Error - timeout of 30000ms exceeded
2021-11-08T21:05:30: Error - timeout of 30000ms exceeded
2021-11-08T21:10:31: Error - timeout of 30000ms exceeded
2021-11-08T21:15:31: Error - timeout of 30000ms exceeded
2021-11-08T21:50:30: Error - timeout of 30000ms exceeded
2021-11-08T21:55:30: Error - timeout of 30000ms exceeded
2021-11-08T23:46:00: Error - timeout of 30000ms exceeded
mothluin-error__2021-11-09_00-00-00.log (END)
```

```
2021-11-07T04:45:01: Error - timeout of 30000ms exceeded
2021-11-07T06:50:00: Error - timeout of 30000ms exceeded
2021-11-07T12:20:33: Error - timeout of 30000ms exceeded
2021-11-07T17:04:01: Error - timeout of 30000ms exceeded
2021-11-07T19:19:01: Error - timeout of 30000ms exceeded
2021-11-07T20:40:34: Error - timeout of 30000ms exceeded
2021-11-07T23:50:03: Error - Request failed with status code 400
mothluin-error__2021-11-08_00-00-00.log (END)

```

A broader search highlights a couple errors in the past months:

```
root@localhost:~/.pm2/logs# grep failed mothluin-error__2021-*
mothluin-error__2021-10-04_00-00-00.log:2021-10-03T22:35:13: Error - Request failed with status code 504
mothluin-error__2021-10-04_00-00-00.log:2021-10-03T22:51:41: Error - Request failed with status code 504
mothluin-error__2021-10-16_00-00-00.log:2021-10-15T11:43:31: Error - Request failed with status code 500
mothluin-error__2021-10-21_00-00-00.log:2021-10-20T16:30:00: Error - Request failed with status code 503
mothluin-error__2021-10-21_00-00-00.log:2021-10-20T16:30:01: Error - Request failed with status code 503
mothluin-error__2021-10-22_00-00-00.log:2021-10-21T11:10:07: Error - Request failed with status code 500
mothluin-error__2021-10-29_00-00-00.log:2021-10-28T04:50:33: Error - Request failed with status code 520
mothluin-error__2021-11-08_00-00-00.log:2021-11-07T23:50:03: Error - Request failed with status code 400
```

**Comment by Mothluin** [comment]
Assuming your intuition is correct, what would you suggest in this case?
Shall I manually sell everything to let the bot start anew with a blank slate?

**Comment by Thornsnake** [comment]
You can just delete the PortfolioATH file. The bot will then start rebalancing with your already invested coins again and will re-create the PortfolioATH file during the next investment schedule.

**Comment by Mothluin** [comment]
Just moved the PortfolioATH.json file into the /tmp folder and restarted the bot again.
And... I confirm it just started rebalancing again. :)

I guess I need to transfer some USDT then.
If I don't do that, the bot will always skip the investment schedule and therefore no PortfolioATH.json will be created.
And if I'm missing that file, no trailing stop will ever be actioned.

Thanks for your support!

**Comment by Thornsnake** [comment]
Ah, good point. I'll add a check for that later.
If the investment schedule runs and there is no ATH file to be found, it will be created, even if no investment is made.

For now just put in some USDT for at least one investment, yes.
That will work.

**Comment by Mothluin** [comment]
Can confirm in 7 minutes from now 😃

**Comment by Mothluin** [comment]
Confirmed.
File is recreated:

```
{
  "active":false,
  "allTimeHigh":531.07453495256,
  "investment":531.47907649744,
  "resume":0,
  "triggered":false
}
```

The `investment` flag is set as the total amount of the portfolio at the time of file creation.

**Comment by Thornsnake** [comment]
That is working as intended. If coins are found on your portfolio during the first investment schedule, they are added as initial investment. Otherwise the trailing stop would immediately be armed.

**Comment by Mothluin** [comment]
Yes, I understand what you mean.
Even if the bot failed at selling all the coins due to - we assume - Exchange downtime, the fact the trailing stop triggered means an "investment cycle" was over.
When starting a new cycle, the bot would then populate the `investment` flag with the current value of the portfolio.

I don't want to mess around too much manually with files and configs (that would defeat the purpose of having a bot in first place) but in case I wanted to "restore" the status of the previous cycle I should just edit the `investment` value back to its previous amount, right?
That would instantly arm the trailing stop, which will be triggered at the `MIN_DROP`.

How often the PortfolioATH.json is updated by the bot?
Every 30 seconds, due to the cron scheduling of the same task?

Thanks

**Comment by Thornsnake** [comment]
You would just edit the investment and allTimeHigh values back to their previous amount, yes.

That is not necessary if your only goal is to have the trailing stop armed though. For that you can just set the active value to true. It will then sell after dropping by `MIN_DROP`.

The trailing stop check happens ever minute, at the 30 second mark.

**Comment by Mothluin** [comment]
Aw, right.
That's what you said before:

> From that moment on, the `investment` option doesn't matter anymore.

I have another probably stupid question here.
If I add funds in my quote currency during an investment cycle, will that amount count towards the `allTimeHigh` flag only or even the `investment` value?

**Comment by Thornsnake** [comment]
It will not count towards either.

The investment value will go up during an investment cycle by exactly the amount that was invested.
Your portfolio worth which the allTimeHigh value is calculated with consists of all coins except your quote currency.
